language: java
before_install:
  - wget http://dl.google.com/android/android-sdk_r21.0.1-linux.tgz
  - tar -zxf android-sdk_r21.0.1-linux.tgz
  - export ANDROID_HOME=~/builds/square/otto/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
  - TOOLS=$(android list sdk --no-ui | grep "Android SDK Platform-tools" | cut -d"-" -f1)
  - android update sdk --filter "$TOOLS" --no-ui --force
  - SDK=$(android list sdk --no-ui | grep ", API 16," | cut -d"-" -f1)
  - android update sdk --filter "$SDK" --no-ui --force
  - sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install: /bin/true # install is handled by Maven itself
script: mvn clean install
